title: 学校
subtitle: 学校的一些乱七八糟的网站

# 指定使用的模板文件名，现有页面模板可见templates\pages
template: articles

categories:
  - name: 学校网站
    icon: fas fa-pen
    sites:
      - name: ehall教务系统
        icon: fas fa-user-graduate
        description: 教务系统
        url: "https://ehall.ynu.edu.cn/new/index.html"
      - name: 财务系统
        icon: fas fa-money-bill
        description: 财务系统
        url: "https://www.cwc.ynu.edu.cn/index.htm"
      - name: MOOC
        icon: fas fa-chalkboard-teacher
        description: 慕课
        url: "https://www.icourse163.org/"
      - name: 超星学习通
        icon: fas fa-book
        description: 学习通
        url: "https://i.chaoxing.com/"  
      - name: 知到智慧树
        icon: fas fa-graduation-cap
        description: 知到智慧树
        url: "https://onlineweb.zhihuishu.com/"  